version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        PYTHON_VERSION: $PYTHON_VERSION
    ports: 
      - "5000:5000"
    volumes:
      - ./test.py:/test.py
    command: python3 ./test.py